spring:
  application:
    name: product-center
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.215.217:8848
logging:
  config: classpath:logback-spring.xml
server:
  port: 8085
  servlet:
    context-path: /product-center
