spring:
  application:
    name: pay-center
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.215.217:8848
        register-enabled: true
        namespace: ab65f2cd-3b3e-4489-b07b-df4618217576
        group: dev-test
feign:
#  hystrix:
#    enabled: true
  client:
    config:
      default:
        readTimeout: 5000

#order-center2:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #                                 com.netflix.loadbalancer.BestAvailableRule  #配置规则 最空闲连接策略
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
server:
  port: 8083
#  servlet:
#    context-path: /pay-center