server:
  port: 8084
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: order-center-route
          uri: lb://order-centers
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/order-center/**
          filters:
            - AddResponseHeader=X-Response-Foo,Bar
               discovery:
        locator:
          enabled: true
      default-filters:
    nacos:
      discovery:
        server-addr: 47.97.215.217:8848
