server:
  port: 8084
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: order-center-route
          uri: lb://order-center
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/order/**
          filters:
            - AddResponseHeader=X-Response-Foo,Bar
            - PreserveHostHeader
            - TokenValidate
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 47.97.215.217:8848
        namespace: ab65f2cd-3b3e-4489-b07b-df4618217576
        group: dev-test
feign:
  client:
    config:
      default:
        readTimeout: 5000
