server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          url-expression: lb://order-center
          route-id-prefix: order-center
    nacos:
      discovery:
        server-addr: 47.97.215.217:8848
